#!/bin/bash -v

mamba env list
mamba init
mamba activate uw2-coupling

# Build / install the uw2 in this repo

git clone --single-branch --branch v2.17.x https://github.com/underworldcode/underworld2.git
cd underworld2
pip install . --no-build-isolation
cd ..

git clone --single-branch https://github.com/NengLu/binder-uwg-coupling-test ./uw-coupling-test

echo
echo "Build at" > ~/.time_of_env_creation
date >> ~/.time_of_env_creation
echo
